import React from "react";
import { MainNavigation } from "components/MainNavigation";
import { Button } from "components/Button";
import { useNavigate } from "react-router-dom";
import { Toaster } from "components/Toast";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <>
      <Toaster />
      <MainNavigation />
      <div className="min-h-screen bg-white">
        {/* Header */}
        <header className="border-b">
          <div className="container mx-auto px-4 py-4 flex justify-between items-center">
            <div className="flex items-center space-x-2">
              <div className="h-8 w-8 rounded-md bg-blue-600 flex items-center justify-center text-white font-bold">M</div>
              <h1 onClick={() => navigate('/')} className="text-xl font-bold cursor-pointer">TheMoneyGate</h1>
            </div>
            <nav>
              <ul className="flex space-x-6 items-center">
                <li><a href="/#how-it-works" className="text-zinc-600 hover:text-blue-600 transition-colors">How It Works</a></li>
                <li><a href="/features" className="text-zinc-600 hover:text-blue-600 transition-colors">Features</a></li>
                <li><a href="/pricing" className="text-zinc-600 hover:text-blue-600 transition-colors">Pricing</a></li>
                <li>
                  <Button 
                    variant="primary" 
                    onClick={() => navigate('/login')}
                  >
                    Get Started
                  </Button>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        <main className="py-12">
          <div className="container mx-auto px-4 max-w-4xl">
            <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
            
            <div className="prose max-w-none">
              <p className="text-lg mb-6">Last Updated: March 9, 2025</p>
              
              <p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using TheMoneyGate website (the "Service") operated by TheMoneyGate, Inc. ("us", "we", or "our").</p>
              
              <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>
              
              <p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">1. Accounts</h2>
              
              <p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
              
              <p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>
              
              <p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">2. Intellectual Property</h2>
              
              <p>The Service and its original content, features and functionality are and will remain the exclusive property of TheMoneyGate, Inc. and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of TheMoneyGate, Inc.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">3. Content Generated by the Service</h2>
              
              <p>TheMoneyGate provides tools that may generate content, tools, and templates for your use. You retain ownership of any content you create using our Service, however, by using our Service to generate such content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, translate, and distribute such content in any media.</p>
              
              <p>You are responsible for ensuring that any content you create with our tools does not infringe upon the intellectual property rights of others. We are not responsible for any legal issues arising from your use of our content generation tools.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">4. Subscriptions</h2>
              
              <p>Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in advance on a recurring and periodic basis ("Billing Cycle"). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription.</p>
              
              <p>At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or TheMoneyGate, Inc. cancels it. You may cancel your Subscription renewal either through your online account management page or by contacting TheMoneyGate, Inc. customer support team.</p>
              
              <p>A valid payment method, including credit card or PayPal, is required to process the payment for your Subscription. You shall provide TheMoneyGate, Inc. with accurate and complete billing information including full name, address, state, zip code, telephone number, and a valid payment method information. By submitting such payment information, you automatically authorize TheMoneyGate, Inc. to charge all Subscription fees incurred through your account to any such payment instruments.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">5. Links To Other Web Sites</h2>
              
              <p>Our Service may contain links to third-party web sites or services that are not owned or controlled by TheMoneyGate, Inc.</p>
              
              <p>TheMoneyGate, Inc. has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that TheMoneyGate, Inc. shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
              
              <p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">6. Termination</h2>
              
              <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
              
              <p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">7. Limitation Of Liability</h2>
              
              <p>In no event shall TheMoneyGate, Inc., nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">8. Disclaimer</h2>
              
              <p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>
              
              <p>TheMoneyGate, Inc. its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">9. Governing Law</h2>
              
              <p>These Terms shall be governed and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.</p>
              
              <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">10. Changes</h2>
              
              <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
              
              <p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>
              
              <h2 className="text-2xl font-bold mt-8 mb-4">11. Contact Us</h2>
              
              <p>If you have any questions about these Terms, please contact us:</p>
              
              <ul className="list-disc pl-6 mt-2">
                <li>By email: support@themoneygate.com</li>
                <li>By phone: +1 (555) 123-4567</li>
                <li>By mail: 123 Money Door Street, San Francisco, CA 94103</li>
              </ul>
            </div>
            
            <div className="mt-12 text-center">
              <p className="text-zinc-600 mb-4">Have questions about our Terms and Conditions?</p>
              <Button 
                variant="outline"
                onClick={() => navigate('/contact')}
              >
                Contact Us
              </Button>
            </div>
          </div>
        </main>

        {/* Footer */}
        <footer className="bg-zinc-900 text-zinc-400 py-12 mt-12">
          <div className="container mx-auto px-4">
            <div className="flex flex-col md:flex-row justify-between">
              <div className="mb-8 md:mb-0">
                <div className="flex items-center space-x-2 mb-4">
                  <div className="h-8 w-8 rounded-md bg-blue-600 flex items-center justify-center text-white font-bold">M</div>
                  <h1 className="text-xl font-bold text-white">TheMoneyGate</h1>
                </div>
                <p className="max-w-xs">Helping digital entrepreneurs discover profitable content opportunities through Hidden Money Doors.</p>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-8">
                <div>
                  <h3 className="text-white font-semibold mb-4">Platform</h3>
                  <ul className="space-y-2">
                    <li><a href="/#how-it-works" className="hover:text-white transition-colors">How It Works</a></li>
                    <li><a href="/features" className="hover:text-white transition-colors">Features</a></li>
                    <li><a href="/pricing" className="hover:text-white transition-colors">Pricing</a></li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-white font-semibold mb-4">Resources</h3>
                  <ul className="space-y-2">
                    <li><a href="/blog" className="hover:text-white transition-colors">Blog</a></li>
                    <li><a href="/guides" className="hover:text-white transition-colors">Guides</a></li>
                    <li><a href="/support" className="hover:text-white transition-colors">Support</a></li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-white font-semibold mb-4">Company</h3>
                  <ul className="space-y-2">
                    <li><a href="/about" className="hover:text-white transition-colors">About</a></li>
                    <li><a href="/contact" className="hover:text-white transition-colors">Contact</a></li>
                    <li><a href="/terms" className="hover:text-white transition-colors">Terms</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="border-t border-zinc-800 mt-12 pt-8 text-center text-sm">
              © {new Date().getFullYear()} TheMoneyGate. All rights reserved.
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}