
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const About = lazy(() => import("./pages/About.tsx"));
const AdminDashboard = lazy(() => import("./pages/AdminDashboard.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const AuthDebug = lazy(() => import("./pages/AuthDebug.tsx"));
const Blog = lazy(() => import("./pages/Blog.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const EmbedPreview = lazy(() => import("./pages/EmbedPreview.tsx"));
const EmbedTool = lazy(() => import("./pages/EmbedTool.tsx"));
const Features = lazy(() => import("./pages/Features.tsx"));
const GeneratedTools = lazy(() => import("./pages/GeneratedTools.tsx"));
const Guides = lazy(() => import("./pages/Guides.tsx"));
const KeywordResearch = lazy(() => import("./pages/KeywordResearch.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Pricing = lazy(() => import("./pages/Pricing.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Subscription = lazy(() => import("./pages/Subscription.tsx"));
const Support = lazy(() => import("./pages/Support.tsx"));
const Terms = lazy(() => import("./pages/Terms.tsx"));
const ToolGenerator = lazy(() => import("./pages/ToolGenerator.tsx"));
const ToolMonetization = lazy(() => import("./pages/ToolMonetization.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/about", element: <UserGuard><About /></UserGuard>},
	{ path: "/admin-dashboard", element: <UserGuard><AdminDashboard /></UserGuard>},
	{ path: "/admindashboard", element: <UserGuard><AdminDashboard /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/auth-debug", element: <UserGuard><AuthDebug /></UserGuard>},
	{ path: "/authdebug", element: <UserGuard><AuthDebug /></UserGuard>},
	{ path: "/blog", element: <UserGuard><Blog /></UserGuard>},
	{ path: "/contact", element: <UserGuard><Contact /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/embed-preview", element: <UserGuard><EmbedPreview /></UserGuard>},
	{ path: "/embedpreview", element: <UserGuard><EmbedPreview /></UserGuard>},
	{ path: "/embed-tool", element: <UserGuard><EmbedTool /></UserGuard>},
	{ path: "/embedtool", element: <UserGuard><EmbedTool /></UserGuard>},
	{ path: "/features", element: <UserGuard><Features /></UserGuard>},
	{ path: "/generated-tools", element: <UserGuard><GeneratedTools /></UserGuard>},
	{ path: "/generatedtools", element: <UserGuard><GeneratedTools /></UserGuard>},
	{ path: "/guides", element: <UserGuard><Guides /></UserGuard>},
	{ path: "/keyword-research", element: <UserGuard><KeywordResearch /></UserGuard>},
	{ path: "/keywordresearch", element: <UserGuard><KeywordResearch /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/pricing", element: <UserGuard><Pricing /></UserGuard>},
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard>},
	{ path: "/subscription", element: <UserGuard><Subscription /></UserGuard>},
	{ path: "/support", element: <UserGuard><Support /></UserGuard>},
	{ path: "/terms", element: <UserGuard><Terms /></UserGuard>},
	{ path: "/tool-generator", element: <UserGuard><ToolGenerator /></UserGuard>},
	{ path: "/toolgenerator", element: <UserGuard><ToolGenerator /></UserGuard>},
	{ path: "/tool-monetization", element: <UserGuard><ToolMonetization /></UserGuard>},
	{ path: "/toolmonetization", element: <UserGuard><ToolMonetization /></UserGuard>},

];
